name: Expressions & Contexts

on: [push, pull_request, workflow_dispatch]

run-name: 'Expressions & Contexts by @${{ github.actor }}, event: ${{ github.event_name }}'

jobs:
  using-expressions-and-contexts:
    if: contains(fromJson('["issues", "pull_request"]'), github.event_name)
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'string' }}
          echo ${{ true && false }}
      - name: Dump Contexts
        run: |
          cat <<EOF
          ${{ toJson(github.event.pull_request.labels[*].name) }}'
          EOF
#          cat <<EOF
#          ${{ toJson(github) }}'
#          EOF
#          cat <<EOF
#          ${{ toJson(job) }}
#          EOF
#          cat <<EOF
#          ${{ toJson(secrets) }}
#          EOF
#          cat <<EOF
#          ${{ toJson(steps) }}
#          EOF
#          cat <<EOF
#          ${{ toJson(runner) }}
#          EOF
